M48
; DRILL file {KiCad 6.0.0} date Tue 22 Mar 2022 08:10:52 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-22T20:10:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X108.145Y-44.285
X108.145Y-74.285
X161.145Y-44.285
X161.145Y-74.285
T0
M30
